name: publish-prettier-config-npm-package
on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Debug info
        run: |
          echo ${{ secrets.GITHUB_TOKEN }}
          echo ${{ secrets.NPM_TOKEN }}
          echo ${{ secrets.NODE_AUTH_TOKEN_3 }}
          echo ${{ secrets.NODE_AUTH_TOKEN_2 }}

      - name: npm package publish
        run: npm publish --provenance --access public --verbose
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug info
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Registry: $(npm config get registry)"
          npm whoami

          
# name: publish-prettier-config-npm-package
# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     name: Build and push image
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/setup-node@master
#         with:
#           version: 12
#           registry-url: 'https://registry.npmjs.org'
#       - uses: shawnbot/npm-publish-action@master
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
